"""Canonical field definitions used across workflows."""

CANONICAL_FIELDS = {
    "person_id": "Stable record identifier when available.",
    "first_name": "Primary given name.",
    "middle_name": "Middle name or initial.",
    "last_name": "Family name.",
    "primary_address1": "Street address line 1.",
    "primary_address2": "Street address line 2 or unit.",
    "mail_city": "Mailing city/locality.",
    "mail_state": "Mailing province/state/region.",
    "mail_zip": "Mailing postal or zip code.",
    "primary_city": "Primary city/locality on reference files.",
    "primary_state": "Primary province/state/region on reference files.",
    "primary_zip": "Primary postal or zip code on reference files.",
    "email": "Single preferred email field.",
    "phone": "Single preferred phone field.",
    "membership_end_date": "Membership or subscription end date.",
    "created_at": "Record creation or activity date.",
    "amount": "Money amount stored as text until normalized.",
}


FIELD_ALIASES = {
    "person_id": ["id", "userid", "external_id", "constituentid", "constituantid", "signup_external_id", "personid"],
    "first_name": ["firstname", "first", "givenname", "given_name"],
    "middle_name": ["middlename", "middle", "middleinitial", "middle_initial"],
    "last_name": ["lastname", "last", "surname", "familyname", "family_name"],
    "primary_address1": [
        "address1",
        "streetaddress",
        "street_address",
        "fullresidentialaddress",
        "mailingaddress1",
        "mailingaddress",
        "residentialaddress",
        "mailing_address",
        "residential_address",
    ],
    "primary_address2": ["address2", "unit", "suite", "apt", "mailingaddress2"],
    "mail_city": [
        "city",
        "mailcity",
        "mail_city",
        "mailingcity",
        "mailing_city",
        "mailmunisipality",
        "mailmunicipality",
    ],
    "mail_state": [
        "state",
        "province",
        "mailstate",
        "mail_state",
        "mailingstate",
        "mailing_state",
        "mailingprovince",
        "mailing_province",
        "mailprovince",
    ],
    "mail_zip": [
        "zip",
        "zipcode",
        "postalcode",
        "postal_code",
        "mailzip",
        "mail_zip",
        "mailingzip",
        "mailing_zip",
        "mailingpostalcode",
        "mailing_postal_code",
        "mailpostalcode",
    ],
    "primary_city": ["primarycity", "city", "rescity", "res_city", "resmunisipality", "resmunicipality"],
    "primary_state": ["primarystate", "province", "state", "resprov", "res_prov", "resprovince"],
    "primary_zip": ["primaryzip", "zipcode", "postalcode", "postal_code", "zip", "respostcode", "res_post_code", "respostalcode"],
    "email": ["email1", "emailaddress", "email_address"],
    "phone": ["phone1", "phonenumber", "phone_number", "mobile", "mobile_phone"],
    "membership_end_date": ["membershipenddate", "memb_exp_date", "expirydate"],
    "created_at": ["date", "created", "createddate", "lastdonationdate"],
    "amount": ["value", "donationamount", "lastdonationreceiptableamount"],
}


FIELD_GROUPS = {
    "identity": ["person_id", "first_name", "middle_name", "last_name"],
    "address_primary": ["primary_address1", "primary_address2", "primary_city", "primary_state", "primary_zip"],
    "address_mailing": ["primary_address1", "primary_address2", "mail_city", "mail_state", "mail_zip"],
    "contact": ["email", "phone"],
}
